services:
  - type: web
    name: ai-agent-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GOOGLE_API_KEY
        sync: false
      - key: SERP_API_KEY
        sync: false
